// <auto-generated />
using System;
using Back.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Back.Migrations
{
    [DbContext(typeof(IgraonicaContext))]
    partial class IgraonicaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Back.Models.BoardGame", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojIgraca")
                        .HasColumnType("int")
                        .HasColumnName("BrojIgraca");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.Property<int?>("PlayingPlaceID")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Tip");

                    b.HasKey("ID");

                    b.HasIndex("PlayingPlaceID");

                    b.ToTable("BoardGame");
                });

            modelBuilder.Entity("Back.Models.Igraonica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("M")
                        .HasColumnType("int")
                        .HasColumnName("M");

                    b.Property<int>("N")
                        .HasColumnType("int")
                        .HasColumnName("N");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Igraonica");
                });

            modelBuilder.Entity("Back.Models.Sto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Boja")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Boja");

                    b.Property<int>("BrojIgraca")
                        .HasColumnType("int")
                        .HasColumnName("BrojIgraca");

                    b.Property<int>("I")
                        .HasColumnType("int")
                        .HasColumnName("I");

                    b.Property<int?>("IgraID")
                        .HasColumnType("int");

                    b.Property<int>("J")
                        .HasColumnType("int")
                        .HasColumnName("J");

                    b.Property<int>("MaxBrojIgraca")
                        .HasColumnType("int")
                        .HasColumnName("MaxBrojIgraca");

                    b.Property<int?>("PlayingPlaceID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IgraID");

                    b.HasIndex("PlayingPlaceID");

                    b.ToTable("Sto");
                });

            modelBuilder.Entity("Back.Models.BoardGame", b =>
                {
                    b.HasOne("Back.Models.Igraonica", "PlayingPlace")
                        .WithMany("Igre")
                        .HasForeignKey("PlayingPlaceID");

                    b.Navigation("PlayingPlace");
                });

            modelBuilder.Entity("Back.Models.Sto", b =>
                {
                    b.HasOne("Back.Models.BoardGame", "Igra")
                        .WithMany()
                        .HasForeignKey("IgraID");

                    b.HasOne("Back.Models.Igraonica", "PlayingPlace")
                        .WithMany("Stolovi")
                        .HasForeignKey("PlayingPlaceID");

                    b.Navigation("Igra");

                    b.Navigation("PlayingPlace");
                });

            modelBuilder.Entity("Back.Models.Igraonica", b =>
                {
                    b.Navigation("Igre");

                    b.Navigation("Stolovi");
                });
#pragma warning restore 612, 618
        }
    }
}
